# Generated by Django 5.2.3 on 2025-06-17 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_clothingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='assistant.profile'),
        ),
    ]
