# Generated by Django 5.2.3 on 2025-06-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_clothingitem_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('accessory', 'Accessory'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
