# Generated by Django 5.2.3 on 2025-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_clothingitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='category',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='fine_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
