# Generated by Django 5.2.3 on 2025-06-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_remove_clothingitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='fine_category',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('accessory', 'Accessory'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
