# Generated by Django 5.2.3 on 2025-06-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_remove_clothingitem_fine_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='category',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='fine_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
