# Generated by Django 5.2.3 on 2025-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_remove_clothingitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='fine_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
