# Generated by Django 5.2.3 on 2025-07-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_alter_clothingitem_fine_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_outfits/')),
                ('description', models.TextField(blank=True)),
                ('predicted_style', models.CharField(blank=True, max_length=50)),
                ('detected_labels', models.TextField(blank=True)),
                ('fine_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_outfits', to='assistant.profile')),
            ],
        ),
    ]
