# Generated by Django 5.2.3 on 2025-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_useroutfit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroutfit',
            name='created_at',
        ),
        migrations.AddField(
            model_name='useroutfit',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useroutfit',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useroutfit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useroutfit',
            name='detected_labels',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useroutfit',
            name='fine_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useroutfit',
            name='image',
            field=models.ImageField(upload_to='outfits/'),
        ),
        migrations.AlterField(
            model_name='useroutfit',
            name='predicted_style',
            field=models.CharField(max_length=100),
        ),
    ]
